AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    # Right now, there's a lot of code in config that I didn't write that violates the rules.
    - 'config/**/*'

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
