sudo: false
language: ruby
rvm: 2.3.4
env:
- DB: postgresql
before_script:
- psql -c 'create database timesheet_test;' -U postgres
script:
- bundle exec rake test
notifications:
  email: jonarnett90@gmail.com
