version: '2'
services:
  db:
    image: postgres

  web:
    build: .
    command: bundle exec passenger start -p 8000
    environment:
      RAILS_ENV: development
    ports:
      - "8000:8000"
    depends_on:
      - db
