default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  password:
  host: db

development:
  <<: *default
  database: timesheet-dev

test:
  <<: *default
  database: timesheet_test

staging: &staging
  <<: *default
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  database: <%= ENV["DB_NAME"] %>

production:
  <<: *staging
