default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: timesheet-dev

test:
  <<: *default
  database: timesheet-test

production:
  <<: *default
  database: timesheet
